## EAI Lab Assignment - 3 (Search Strategy)
Shobhit Kumar - 19MCME16

In [2]:
import numpy as np
from queue import Queue
import time

### Utility Functions

In [5]:
# Function to check if the move is valid or not
def is_valid(board, indices, size):
    rows = indices[0]
    cols = indices[1]

    col_sum = np.sum(board, axis=0)

    # Column sum condition
    if ((col_sum > 1).sum() > 0):
        return False
    
    # Diagonal Condition

    # Up-Left direction
    i = rows - 1
    j = cols - 1
    up_left = True
    while (i >= 0 and j >= 0):
        if board[i, j] == 1:
            up_left = False
            break
        i = i - 1
        j = j - 1

    # Down-Right direction
    i = rows + 1
    j = cols + 1
    down_right = True
    while (i < size and j < size):
        if board[i, j] == 1:
            down_right = False
            break
        i = i + 1
        j = j + 1

    # Up-Right direction
    i = rows - 1
    j = cols + 1
    up_right = True
    while (i >= 0 and j < size):
        if board[i, j] == 1:
            up_right = False
            break
        i = i - 1
        j = j + 1

    # Down-Left direction
    i = rows + 1
    j = cols - 1
    down_left = True
    while (i < size and j >= 0):
        if board[i, j] == 1:
            down_left = False
            break
        i = i + 1
        j = j - 1

    if (up_left and down_right and up_right and down_left):
        return True
    
    return False

# Function to check if the node is goal node or not  
def is_goal(node, size):
    board = node[0]
    ones = np.ones(size)

    row_sum = np.sum(board, axis=1)
    col_sum = np.sum(board, axis=0)

    comp_row = row_sum == ones
    comp_col = col_sum == ones
    if (comp_row.all() and comp_col.all()):
        return True
    return False


### Breadth First Search

In [3]:
def breadth_first_search(size):
    if (size <= 0):
        print("Invalid Size!")
        return
        
    board = np.zeros((size, size))
    indices = (None, None)
    sol_found = False

    frontier = Queue()
    frontier.put((board, indices))

    while not frontier.empty():
        node = frontier.get()
        # print(node[0])

        # Checking if node is goal node
        if (is_goal(node, size)):
            sol_found = True
            print("Found Solution")
            print(node[0])
            return

        # Expanding the tree
        for col in range(size):
            temp = node[0].copy()
            row = node[1][0]

            if (row == None):
                temp[0, col] = 1
                indices = (0, col)
                frontier.put((temp, indices))
            else:
                temp[row + 1, col] = 1
                indices = (row + 1, col)
                
                # Check if move is valid
                if (is_valid(temp, indices, size)):
                    frontier.put((temp, indices))
    if not sol_found:
        print("Solution not Found!")

In [4]:
start = time.time()
breadth_first_search(4)
ex_time = time.time() - start
print(f"Execution Time: {ex_time*10**3:.4f} ms")

Found Solution
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
Execution Time: 7.5717 ms


### Depth First Search

In [64]:
def depth_first_search(size):
    if (size <= 0):
        print("Invalid Size!")
        return
        
    board = np.zeros((size, size))
    indices = (None, None)
    sol_found = False

    frontier = []
    frontier.append((board, indices))

    while len(frontier) != 0:
        node = frontier.pop()
        # print(node[0])

        # Checking if node is goal node
        if (is_goal(node, size)):
            sol_found = True
            print("Found Solution")
            print(node[0])
            return

        # Expanding the tree
        for col in range(size):
            temp = node[0].copy()
            row = node[1][0]

            if (row == None):
                temp[0, col] = 1
                indices = (0, col)
                frontier.append((temp, indices))
            else:
                temp[row + 1, col] = 1
                indices = (row + 1, col)
                
                # Check if move is valid
                if (is_valid(temp, indices, size)):
                    frontier.append((temp, indices))
    if not sol_found:
        print("Solution not Found!")

In [75]:
start = time.time()
depth_first_search(4)
ex_time = time.time() - start
print(f"Execution Time: {ex_time*10**3:.4f} ms")

Found Solution
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Execution Time: 1.5843 ms


### Depth Limit Search

In [67]:
def depth_limit_search(size, limit):
    if (size <= 0):
        print("Invalid Size!")
        return False
    if (limit < 0):
        print("Invalid Limit!")
        return False

    board = np.zeros((size, size))
    indices = (None, None)
    sol_found = False

    frontier = []
    frontier.append((board, indices))

    while len(frontier) != 0:
        node = frontier.pop()
        # print(node[0])

        # Checking if node is goal node
        if (is_goal(node, size)):
            sol_found = True
            print("Found Solution")
            print(node[0])
            return True

        # Expanding the tree
        for col in range(size):
            temp = node[0].copy()
            row = node[1][0]

            if (row == None):
                depth = 0
                if (depth < limit):
                    temp[0, col] = 1
                    indices = (0, col)
                    frontier.append((temp, indices))
            else:
                temp[row + 1, col] = 1
                indices = (row + 1, col)
                depth = row + 1
                if (depth < limit):
                    # Check if move is valid
                    if (is_valid(temp, indices, size)):
                        frontier.append((temp, indices))
    if not sol_found:
        print("Solution not Found!")
        return False

In [69]:
start = time.time()
depth_limit_search(4, 4)
ex_time = time.time() - start
print(f"Execution Time: {ex_time*10**3:.4f} ms")

Found Solution
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Execution Time: 1.5509 ms


### Iterative Deepening Search

In [79]:
def iterative_deepening_search(size):
    if (size <= 3):
        print("Cannot Find Solution!")
        return
    depth = 0
    sol_found = False

    while not sol_found:
        print(f"Depth: {depth}")
        sol_found = depth_limit_search(size, depth)
        depth = depth + 1

In [85]:
start = time.time()
iterative_deepening_search(4)
ex_time = time.time() - start
print(f"Execution Time: {ex_time*10**3:.4f} ms")

Depth: 0
Solution not Found!
Depth: 1
Solution not Found!
Depth: 2
Solution not Found!
Depth: 3
Solution not Found!
Depth: 4
Found Solution
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Execution Time: 4.5750 ms


### Uniform Cost Search

In [1]:
import sys
class PriorityQueue:
    def __init__(self):
        self.queue = []

    def empty(self):
        return len(self.queue) == 0

    def insert(self, node):
        self.queue.append(node)

    def pop(self):
        try:
            priority = sys.maxsize
            p_index = 0
            for i in range(len(self.queue)):
                if self.queue[i][2] < priority:
                    priority = self.queue[i][2]
                    p_index = i
            node = self.queue[p_index]
            del self.queue[p_index]
            return node
        except IndexError:
            print("Error: IndexError!")
            exit()

    def emptyQueue(self):
        while not self.empty():
            self.pop()

In [87]:
def uniform_cost_search(size):
    if (size <= 0):
        print("Invalid Size!")
        return
        
    board = np.zeros((size, size))
    indices = (None, None)
    cost = size
    sol_found = False

    frontier = PriorityQueue()
    frontier.insert((board, indices, cost))

    while not frontier.empty():
        node = frontier.pop()
        # print(node[0])

        # Checking if node is goal node
        if (is_goal(node, size)):
            sol_found = True
            print("Found Solution")
            # print(f'Cost: {node[2]}')
            print(node[0])
            # return
            continue

        # Expanding the tree
        for col in range(size):
            temp = node[0].copy()
            row = node[1][0]
            cost = node[2] - 1

            if (row == None):
                temp[0, col] = 1
                indices = (0, col)
                frontier.insert((temp, indices, cost))
            else:
                temp[row + 1, col] = 1
                indices = (row + 1, col)
                
                # Check if move is valid
                if (is_valid(temp, indices, size)):
                    frontier.insert((temp, indices, cost))
    if not sol_found:
        print("Solution not Found!")

In [89]:
start = time.time()
uniform_cost_search(4)
ex_time = time.time() - start
print(f"Execution Time: {ex_time*10**3:.4f} ms")

Found Solution
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
Found Solution
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Execution Time: 4.2818 ms


### Greedy Best First Search

In [90]:
def greedy_bfs(size):
    if (size <= 0):
        print("Invalid Size!")
        return
        
    board = np.zeros((size, size))
    indices = (None, None)
    cost = size**size
    sol_found = False

    frontier = PriorityQueue()
    frontier.insert((board, indices, cost))

    while not frontier.empty():
        node = frontier.pop()
        # print(node[0])

        # Checking if node is goal node
        if (is_goal(node, size)):
            sol_found = True
            print("Found Solution")
            # print(f'Cost: {node[2]}')
            print(node[0])
            return

        # Expanding the tree
        for col in range(size):
            temp = node[0].copy()
            row = node[1][0]

            if (row == None):
                temp[0, col] = 1
                indices = (0, col)
                cost = size**(size-1)
                frontier.insert((temp, indices, cost))
            else:
                temp[row + 1, col] = 1
                indices = (row + 1, col)
                cost = size**(size - row - 1)
                
                # Check if move is valid
                if (is_valid(temp, indices, size)):
                    frontier.insert((temp, indices, cost))
    if not sol_found:
        print("Solution not Found!")

In [92]:
start = time.time()
greedy_bfs(4)
ex_time = time.time() - start
print(f"Execution Time: {ex_time*10**3:.4f} ms")

Found Solution
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
Execution Time: 2.4652 ms


#### A* Search

In [93]:
def a_star(size):
    if (size <= 0):
        print("Invalid Size!")
        return
        
    board = np.zeros((size, size))
    indices = (None, None)
    gx = size
    hx = size**size
    cost = gx + hx
    sol_found = False

    frontier = PriorityQueue()
    frontier.insert((board, indices, cost, gx))

    while not frontier.empty():
        node = frontier.pop()
        # print(node[0])

        # Checking if node is goal node
        if (is_goal(node, size)):
            sol_found = True
            print("Found Solution")
            # print(f'Cost: {node[2]}')
            print(node[0])
            # return
            continue

        # Expanding the tree
        for col in range(size):
            temp = node[0].copy()
            row = node[1][0]
            gx = node[3] + (node[3] - 1)

            if (row == None):
                temp[0, col] = 1
                indices = (0, col)
                hx = size**(size-1)
                cost = gx + hx
                frontier.insert((temp, indices, cost, gx))
            else:
                temp[row + 1, col] = 1
                indices = (row + 1, col)
                hx = size**(size - row - 1)
                cost = gx + hx

                # Check if move is valid
                if (is_valid(temp, indices, size)):
                    frontier.insert((temp, indices, cost, gx))
    if not sol_found:
        print("Solution not Found!")

In [95]:
start = time.time()
a_star(4)
ex_time = time.time() - start
print(f"Execution Time: {ex_time*10**3:.4f} ms")

Found Solution
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
Found Solution
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
Execution Time: 2.7053 ms


#### Hill Climbing Search

In [6]:
def hill_climbing(size):
    if (size <= 0):
        print("Invalid Size!")
        return
        
    board = np.zeros((size, size))
    indices = (None, None)
    gx = size
    hx = size**size
    cost = gx + hx
    sol_found = False

    frontier = PriorityQueue()
    frontier.insert((board, indices, cost, gx))

    while not frontier.empty():
        # Get the best node
        node = frontier.pop()
        # print(node[0])

        # Empty the queue
        frontier.emptyQueue()

        # Checking if node is goal node
        if (is_goal(node, size)):
            sol_found = True
            print("Found Solution")
            # print(f'Cost: {node[2]}')
            print(node[0])
            return

        # Expanding the tree
        for col in range(size):
            temp = node[0].copy()
            row = node[1][0]
            gx = node[3] + (node[3] - 1)

            if (row == None):
                temp[0, col] = 1
                indices = (0, col)
                hx = size**(size-1)
                cost = gx + hx
                frontier.insert((temp, indices, cost, gx))
            else:
                temp[row + 1, col] = 1
                indices = (row + 1, col)
                hx = size**(size - row - 1)
                cost = gx + hx

                # Check if move is valid
                if (is_valid(temp, indices, size)):
                    frontier.insert((temp, indices, cost, gx))
    if not sol_found:
        print("Solution not Found!")

In [7]:
hill_climbing(4)

Solution not Found!
